[phases.setup]
nixPkgs = ['python311', 'pip']

[phases.install]
cmds = ['python -m pip install --upgrade pip', 'pip install -r requirements.txt']

[phases.build]
cmds = ['echo "Build completed"']

[start]
cmd = 'python -m gunicorn app:app --bind 0.0.0.0:$PORT'